create table user (
	seq NUMBER generated by default as identity,
	email varchar(255) not null,
	name varchar(255) not null,
	picture varchar(255),
	role varchar(255) not null,
	provider varchar(255) not null,
	primary key (seq)
)